### ISSUE TITLE
A few Pylint issues remain I'm afraid!

### ISSUE THREAD

**Issue by MrWako** [bigeagleowl/A-Shaky-Start-Talk-Timer#30]
Hello,

I just re-ran pylint and generated the output below. I have a branch with the required changes on but I can't seem to push it back to GitHub, probably a permissions issue. Let me know if you like me to try again.

No config file found, using default configuration
************* Module main
C:  1, 0: Missing module docstring (missing-docstring)
E:  3, 0: Unable to import 'microbit' (import-error)
W:  3, 0: Wildcard import microbit (wildcard-import)
E:  4, 0: Unable to import 'radio' (import-error)
C:  8, 0: Invalid constant name "shakyId" (invalid-name)
C: 11, 0: Invalid function name "StartUpScreen" (invalid-name)
C: 11, 0: Missing function docstring (missing-docstring)
E: 12, 4: Undefined variable 'display' (undefined-variable)
E: 12,17: Undefined variable 'Image' (undefined-variable)
C: 16, 0: Invalid function name "ShowPowerOn" (invalid-name)
C: 16, 0: Missing function docstring (missing-docstring)
E: 17, 4: Undefined variable 'display' (undefined-variable)
C: 21, 0: Invalid function name "ClearMessageBuffer" (invalid-name)
C: 21, 0: Missing function docstring (missing-docstring)
C: 27, 0: Invalid function name "WaitTillShakingStops" (invalid-name)
C: 27, 0: Missing function docstring (missing-docstring)
E: 28,10: Undefined variable 'accelerometer' (undefined-variable)
C: 33, 0: Invalid function name "GetReadyToGoAgain" (invalid-name)
C: 33, 0: Missing function docstring (missing-docstring)
C: 39, 0: Invalid function name "CountDown" (invalid-name)
C: 39, 0: Missing function docstring (missing-docstring)
W: 39,14: Redefining name 'delay' from outer scope (line 164) (redefined-outer-name)
C: 40, 4: Invalid variable name "x" (invalid-name)
C: 41, 4: Invalid variable name "y" (invalid-name)
E: 42, 4: Undefined variable 'display' (undefined-variable)
C: 44, 8: Invalid variable name "y" (invalid-name)
C: 45,12: Invalid variable name "x" (invalid-name)
E: 48,16: Undefined variable 'sleep' (undefined-variable)
E: 58,37: Undefined variable 'display' (undefined-variable)
E: 63,24: Undefined variable 'display' (undefined-variable)
E: 65,12: Undefined variable 'sleep' (undefined-variable)
E: 66,12: Undefined variable 'display' (undefined-variable)
R: 44, 4: Too many nested blocks (6/5) (too-many-nested-blocks)
C: 72, 0: Invalid function name "DisplayMinutes" (invalid-name)
C: 72, 0: Missing function docstring (missing-docstring)
W: 72,19: Redefining name 'minutes' from outer scope (line 160) (redefined-outer-name)
C: 73, 4: Invalid variable name "x" (invalid-name)
C: 74, 4: Invalid variable name "y" (invalid-name)
C: 77, 8: Invalid variable name "y" (invalid-name)
C: 78,12: Invalid variable name "x" (invalid-name)
E: 81,16: Undefined variable 'display' (undefined-variable)
E: 84,20: Undefined variable 'display' (undefined-variable)
E: 86,20: Undefined variable 'display' (undefined-variable)
C: 89, 0: Invalid function name "GetTalkTime" (invalid-name)
C: 89, 0: Missing function docstring (missing-docstring)
W: 97, 4: Redefining built-in 'quit' (redefined-builtin)
W: 89,16: Redefining name 'minutes' from outer scope (line 160) (redefined-outer-name)
W:107,12: Redefining name 'start' from outer scope (line 191) (redefined-outer-name)
E: 90, 4: Undefined variable 'display' (undefined-variable)
E: 94, 4: Undefined variable 'button_a' (undefined-variable)
E: 95, 4: Undefined variable 'button_b' (undefined-variable)
E:100,28: Undefined variable 'button_a' (undefined-variable)
E:101,14: Undefined variable 'button_b' (undefined-variable)
E:106,11: Undefined variable 'button_a' (undefined-variable)
E:107,20: Undefined variable 'running_time' (undefined-variable)
E:109,18: Undefined variable 'button_a' (undefined-variable)
E:110,19: Undefined variable 'running_time' (undefined-variable)
E:112,20: Undefined variable 'display' (undefined-variable)
C:117, 0: Invalid function name "MinutesToDelay" (invalid-name)
C:117, 0: Missing function docstring (missing-docstring)
W:117,19: Redefining name 'minutes' from outer scope (line 160) (redefined-outer-name)
C:121, 0: Invalid function name "DelayToMinutes" (invalid-name)
C:121, 0: Missing function docstring (missing-docstring)
W:121,19: Redefining name 'delay' from outer scope (line 164) (redefined-outer-name)
C:125, 0: Invalid function name "MessageToDelay" (invalid-name)
C:125, 0: Missing function docstring (missing-docstring)
W:125,19: Redefining name 'receivedmess' from outer scope (line 175) (redefined-outer-name)
C:135, 0: Invalid function name "AbandonTalk" (invalid-name)
C:135, 0: Missing function docstring (missing-docstring)
W:143, 4: Redefining name 'receivedmess' from outer scope (line 175) (redefined-outer-name)
E:136, 7: Undefined variable 'button_a' (undefined-variable)
E:138, 8: Undefined variable 'display' (undefined-variable)
E:138,21: Undefined variable 'Image' (undefined-variable)
E:139,14: Undefined variable 'button_a' (undefined-variable)
C:156, 0: Invalid constant name "on" (invalid-name)
E:156, 5: Undefined variable 'Image' (undefined-variable)
C:160, 0: Invalid constant name "minutes" (invalid-name)
C:164, 0: Invalid constant name "delay" (invalid-name)
C:175, 4: Invalid constant name "receivedmess" (invalid-name)
C:177, 4: Invalid constant name "delayFromRemote" (invalid-name)
C:180, 8: Invalid constant name "delay" (invalid-name)
E:190, 7: Undefined variable 'button_b' (undefined-variable)
C:191, 8: Invalid constant name "start" (invalid-name)
E:191,16: Undefined variable 'running_time' (undefined-variable)
E:193,14: Undefined variable 'button_b' (undefined-variable)
E:196,11: Undefined variable 'running_time' (undefined-variable)
C:197,12: Invalid constant name "delay" (invalid-name)
E:198,12: Undefined variable 'display' (undefined-variable)
E:200, 7: Undefined variable 'button_a' (undefined-variable)
C:201, 8: Invalid constant name "delay" (invalid-name)
E:205, 7: Undefined variable 'accelerometer' (undefined-variable)
C:206, 8: Invalid constant name "send_message" (invalid-name)
E:207,14: Undefined variable 'accelerometer' (undefined-variable)
C:208,12: Invalid constant name "delayFromRemote" (invalid-name)
C:210,16: Invalid constant name "delay" (invalid-name)
C:211,16: Invalid constant name "send_message" (invalid-name)

------------------------------------
Your code has been rated at -8.65/10

**Comment by bigeagleowl** [comment]
Hi @MrWako 

Thank you so much for your help with identifying and fixing linting issues with A Shaky Start Talk Timer ;-)  Your focus on high quality coding practices is very much welcomed & appreciated. 

Yours, Nigel
